### ISSUE TITLE
how to find slash events after block 796425 in kusama

### ISSUE THREAD

**Issue by alexxuyang** [polkascan/polkascan-pre-harvester#6]
seems there isn't any slash events data after block 796425? what is wrong?
https://polkascan.io/pre/kusama/event?module=staking&event=Slash&page=1

**Comment by arjanz** [comment]
It seems like offences are still registered (https://polkascan.io/pre/kusama/event?module=imonline&event=SomeOffline&page=1) but do not result in Slashes. Or do you have reason to believe slash events still occurred? If so, could you provide an example block number?

**Comment by alexxuyang** [comment]
You are right. Although there have some offline events, the slash fraction will be set to ZERO if the number of offenders is below 10% of total. 

https://github.com/paritytech/substrate/blob/af012ea8b12def734cca7ffd2540c6882ecdcbba/frame/im-online/src/lib.rs#L709

https://github.com/paritytech/substrate/blob/af012ea8b12def734cca7ffd2540c6882ecdcbba/frame/staking/src/slashing.rs#L234

https://github.com/paritytech/substrate/blob/af012ea8b12def734cca7ffd2540c6882ecdcbba/frame/staking/src/lib.rs#L2161

https://github.com/paritytech/substrate/blob/af012ea8b12def734cca7ffd2540c6882ecdcbba/frame/staking/src/slashing.rs#L587
